### ISSUE TITLE
Liquibase "diffChangelog" suddenly stops generating migration files

### ISSUE THREAD

**Issue by samuelm00** [liquibase/liquibase-gradle-plugin#143]
Spend quite a long time now on this issue but I don't seem to get to the bottom of this.

This is how I have set up liquibase (and it was working very well for 300+ migrations)

```kotlin
dependencies {
    ...
    liquibaseRuntime("org.liquibase:liquibase-core:4.23.0")
    liquibaseRuntime("org.liquibase:liquibase-groovy-dsl:3.0.3")
    liquibaseRuntime("org.postgresql:postgresql")
    liquibaseRuntime("org.liquibase.ext:liquibase-hibernate6:4.23.0")
    liquibaseRuntime("org.locationtech.jts:jts-core:1.19.0")
    liquibaseRuntime("info.picocli:picocli:4.6.3")
    liquibaseRuntime("org.springframework.boot:spring-boot-starter-data-jpa")
    liquibaseRuntime("org.springframework.security:spring-security-core:6.1.1")
    liquibaseRuntime(sourceSets.main.get().output)
}

...

tasks.getByName("diff").dependsOn("compileJava")
tasks.getByName("diffChangelog").dependsOn("compileJava")

liquibase {
    activities {
        register("main") {
            val fileName = properties.get("fileName") ?: ""
            val url = properties.get("url")
            val userName = properties.get("username")
            val password = properties.get("password")

            val changeLogFileName =
                    "${LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd-HH-mm-ss"))}-${project.name}-${fileName}.xml"
            val classpath = "${project.projectDir}/src/main/resources"
            val directory = "$classpath/db/changelog"

            val liquibaseProps = Properties()
            liquibaseProps.load(file("$classpath/liquibase.properties").inputStream())

            val map = liquibaseProps.map { it.key.toString() to it.value.toString() }.toMap().toMutableMap()
            map["changelog-file"] = "${directory}/${changeLogFileName}"

            if (url != null) {
                map["url"] = url.toString()
            }

            if (userName != null) {
                map["username"] = userName.toString()
            }

            if (password != null) {
                map["password"] = password.toString()
            }

            this.arguments = map.toMap()
        }

        runList = "main"
    }
}

```

The output doesn't show any errors at all and says that everything worked correctly (as it did for the past 300 migrations) but no file is generated. I have not changed anything in my build.gradle file nor have I updated any dependencies. The thing that 's even more confusing to me is that the `diff` command produces the expected output

Any thought on what could be the error?

As reference this is the output of executing `./gradlew :api:diffChangelog -PfileName=FILENAME`

```bash
09:09:04,449 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
09:09:04,449 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:09:04,451 |-ERROR in ch.qos.logback.core.model.processor.ImplicitModelHandler - Could not create component [encoder] of type [net.logstash.logback.encoder.LogstashEncoder] java.lang.ClassNotFoundException: net.logstash.logback.encoder.LogstashEncoder
        at java.lang.ClassNotFoundException: net.logstash.logback.encoder.LogstashEncoder
        at      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at      at ch.qos.logback.core.util.Loader.loadClass(Loader.java:118)
        at      at ch.qos.logback.core.model.processor.ImplicitModelHandler.doComplex(ImplicitModelHandler.java:134)
        at      at ch.qos.logback.core.model.processor.ImplicitModelHandler.handle(ImplicitModelHandler.java:94)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:241)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:210)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:174)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:126)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:69)
        at      at ch.qos.logback.classic.util.DefaultJoranConfigurator.configureByResource(DefaultJoranConfigurator.java:53)
        at      at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:34)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:98)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:77)
        at      at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
        at      at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
        at      at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
        at      at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:121)
        at      at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:95)
        at      at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
        at      at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
        at      at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.<init>(DefaultPersistenceUnitManager.java:103)
        at      at liquibase.ext.hibernate.database.HibernateSpringPackageDatabase.createEntityManagerFactoryBuilder(HibernateSpringPackageDatabase.java:73)
        at      at liquibase.ext.hibernate.database.HibernateEjb3Database.buildMetadataFromPath(HibernateEjb3Database.java:54)
        at      at liquibase.ext.hibernate.database.HibernateDatabase.buildMetadata(HibernateDatabase.java:133)
        at      at liquibase.ext.hibernate.database.HibernateDatabase.setConnection(HibernateDatabase.java:73)
        at      at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:124)
        at      at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:144)
        at      at liquibase.command.core.helpers.AbstractDatabaseConnectionCommandStep.createDatabaseObject(AbstractDatabaseConnectionCommandStep.java:75)
        at      at liquibase.command.core.helpers.ReferenceDbUrlConnectionCommandStep.obtainDatabase(ReferenceDbUrlConnectionCommandStep.java:80)
        at      at liquibase.command.core.helpers.ReferenceDbUrlConnectionCommandStep.run(ReferenceDbUrlConnectionCommandStep.java:61)
        at      at liquibase.command.CommandScope.execute(CommandScope.java:213)
        at      at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at      at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at      at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at      at picocli.CommandLine.access$1300(CommandLine.java:145)
        at      at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at      at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at      at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at      at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at      at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at      at picocli.CommandLine.execute(CommandLine.java:2078)
        at      at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:381)
        at      at liquibase.Scope.child(Scope.java:206)
        at      at liquibase.Scope.child(Scope.java:182)
        at      at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:356)
        at      at liquibase.Scope.child(Scope.java:206)
        at      at liquibase.Scope.child(Scope.java:182)
        at      at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:354)
        at      at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:94)
09:09:04,451 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - Encoder has not been set. Cannot invoke its init method.
09:09:04,451 |-ERROR in ch.qos.logback.core.ConsoleAppender[STDOUT] - No encoder set for the appender named "STDOUT".
09:09:04,451 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
09:09:04,452 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
09:09:04,452 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@74a195a4 - End of configuration.
09:09:04,452 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@76304b46 - Registering current configuration as safe fallback point

BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed. Some database objects and their dependencies cannot be represented automatically, and they may need to be manually updated before being deployed.
Liquibase command 'diff-changelog' was executed successfully.
```

**Comment by samuelm00** [comment]
After quite some struggle I finally figured out the root cause of the problem:

```java
class A {
  @Id
  private Long id;

  @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "bs",
        joinColumns = @JoinColumn(name = "b_id"),
        inverseJoinColumns = @JoinColumn(name = "a_id"))
    private Set<B> bs;
}

class B {
  @Id
  private Long id;

  @ManyToMany(mappedBy = A_.BS, fetch = FetchType.LAZY)
  private Set<A> as;
}
```

Removing the many to many relation fixed the problem. The reason why this so hard to find was that there where no error messages in the output, after setting the log level to `debug` I finally could see this:

```bash
WARNING [liquibase.command] Diff changelog command failed
```

Reproduction steps:
1. Create 2 entities with many to many relationships
2. Run `./gradlew diff` and verify the output (liquibase should produce the expected output here)
3. Run `./gradlew diffChangelog` you should see that everything was successful but no file was generated
4. Run the command above again with `log-level=debug` then you should see 
```bash
WARNING [liquibase.command] Diff changelog command failed
```

**Comment by stevesaliman** [comment]
I have a hunch that this problem is in liquibase itself, and not the plugin which simply acts as a front end to the liquibase code.  

If you use the standalone liquibase CLI to run the `diff` and `diff-changelog` commands, do you get the same result?

If so, then we need to figure out the difference between how the CLI calls liquibase and how the gradle plugin does it.  If not, then I think we can close this issue, and move it to liquibase itself.
