### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: liquibase/Scope

### ISSUE THREAD

**Issue by rmanibus** [liquibase/liquibase-gradle-plugin#156]
I am trying to add this plugin to a quarkus project running on gradle 8.10.2

It is failing with the following stack trace:

```
Caused by: java.lang.NoClassDefFoundError: liquibase/Scope
        at org.liquibase.gradle.ArgumentBuilder.initializeGlobalArguments(ArgumentBuilder.groovy:61)
        at org.liquibase.gradle.ArgumentBuilder$initializeGlobalArguments.call(Unknown Source)
        at org.liquibase.gradle.LiquibasePlugin.applyTasks(LiquibasePlugin.groovy:61)
        at org.liquibase.gradle.LiquibasePlugin$applyTasks$1.callCurrent(Unknown Source)
        at org.liquibase.gradle.LiquibasePlugin.apply(LiquibasePlugin.groovy:33)
        at org.liquibase.gradle.LiquibasePlugin.apply(LiquibasePlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:54)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.ModelDefaultsApplyingPluginTarget.applyImperative(ModelDefaultsApplyingPluginTarget.java:46)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:288)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:148)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:161)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:43)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:98)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:184)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
        at org.gradle.api.internal.project.DefaultProject.apply(DefaultProject.java:1546)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:37)
        at org.gradle.api.Script$apply.callCurrent(Unknown Source)
        at build_1r3w9szv3lr0mydspeirq8i2d.run(/Users/loichermann/workspace/iru/back/build.gradle:2)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 158 more
Caused by: java.lang.ClassNotFoundException: liquibase.Scope
```

**Comment by binoverfl0w** [comment]
@rmanibus do you mind sharing how you resolved this?

**Comment by rmanibus** [comment]
I had a version discrepancy between liquidbase and this extension

**Comment by binoverfl0w** [comment]
I had the correct version, but I had missed the release notes https://github.com/liquibase/liquibase-gradle-plugin/blob/DAT-18607/doc/releases.md where liquibase dependency is also required in the **buildscript** block.
For context I am using it a spring-boot project with gradle (Kotlin DSL). Hope it helps for other people that may run into this.
