### ISSUE TITLE
Accessing changeLogParameters

### ISSUE THREAD

**Issue by cmoisei** [liquibase/liquibase-gradle-plugin#53]
I tried to access the changeLogParameters set in my build gradle file but I can't reach them. Tried both way to acess them tried ${} it's not accessible.

```
liquibase
{
  activities
  {
    main
    {
      url databaseUrl
      username databaseUsername
      password databasePassword
      changeLogFile "changelog/changelog-master.groovy"
      classpath "${projectDir}/src/db"
      changeLogParameters([ dbms: "${database}"])
    }
```

Is there any secret sauce here. Also I'd like to access the *classpath* in the groovy file as well, how can I do that ?

In my groovy file 

```
changeSet(author: 'user', id: 'xyz') {
    sqlFile(path: "changelog/${dbms}/1.0.RELEASE/track/test.sql")
  }
```
The error I got is this...

```
SEVERE 12/3/18 11:51 AM: liquibase: No such property: dbms for class: Script1
groovy.lang.MissingPropertyException: No such property: dbms for class: Script1
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at Script1$_run_closure1.doCall(Script1.groovy:13)
```

Is this a bug ?

My plugin version is 1.2.4

**Comment by stevesaliman** [comment]
I think solving the changelog parameter issue will take care of your `sqlFile` issue.  Assuming that you have a property called `database` defined in your Gradle build, you should be able to simply use `changeLogParameters([ dbms: database])` to pass the value of the build property into Liquibase.

**Comment by cmoisei** [comment]
In the given example, the database was a gradle property via the gradles.properties.
However i have failed to mention that I did try the route you pointed out too. I ha

I don't the params are fed into the changeSet {}

I even tried something like this

```
liquibase
{
  activities
  {
    main
    {
      url databaseUrl
      username databaseUsername
      password databasePassword
      changeLogFile "changelog/changelog-master.groovy"
      classpath "${projectDir}/src/db"
      changeLogParameters([ dbms: 'test'])
    }
    data {
      url databaseUrl
      username databaseUsername
      password databasePassword
      changeLogFile "convert/data/changelog-master.groovy"
      classpath "${projectDir}/src/db"
      changeLogParameters([ dbms:  'test' ])
    }
  }
  runList = project.getRunList().join(',')
  console "Liquibase: ${runList}"
}
```

```
  changeSet(author: 'xxx, id: 'tagDatabase') {
    comment "Main"
    System.out.println("++++++++++++++++++++++++++++++++++++++=>${dbms}" )
```

Same results.... Any idea how to debug this ?

```
SEVERE 12/4/18 10:39 AM: liquibase: No such property: dbms for class: org.liquibase.groovy.delegate.ChangeSetDelegate
groovy.lang.MissingPropertyException: No such property: dbms for class: org.liquibase.groovy.delegate.ChangeSetDelegate
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at Script1$_run_closure1$_closure2.doCall(Script1.groovy:28)
	at Script1$_run_closure1$_closure2.doCall(Script1.groovy)
```

**Comment by stevesaliman** [comment]
Closed for inactivity
