### ISSUE TITLE
JAVA 11+ suport

### ISSUE THREAD

**Issue by josephe-kv** [liquibase/liquibase-gradle-plugin#75]
Hi,
If liquibase gradle plugin is run on JAVA 11 the error is raised:

[main] ERROR liquibase.integration.commandline.Main - Unexpected error running Liquibase: javax.xml.bind.annotation.XmlElement
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
        at liquibase.pro.packaged.ki.<init>(Unknown Source)
        at liquibase.pro.packaged.ki.<init>(Unknown Source)
        at liquibase.pro.packaged.kj.setupModule(Unknown Source)
        at liquibase.pro.packaged.bW.registerModule(Unknown Source)
        at liquibase.pro.packaged.lQ.d_(Unknown Source)
        at liquibase.pro.packaged.ku.a(Unknown Source)
        at liquibase.pro.packaged.ku.a(Unknown Source)
        at liquibase.pro.packaged.kv.a(Unknown Source)
        at liquibase.pro.packaged.kv$a.a(Unknown Source)
        at liquibase.pro.packaged.kv$a$1.f(Unknown Source)
        at liquibase.pro.packaged.ks.a(Unknown Source)
        at liquibase.pro.packaged.kr.a(Unknown Source)
        at liquibase.pro.packaged.kp.a(Unknown Source)
        at liquibase.pro.packaged.kp.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at liquibase.license.LicenseServiceFactory.getLicenseService(LicenseServiceFactory.java:33)
        at liquibase.integration.commandline.Main.run(Main.java:205)
        at liquibase.integration.commandline.Main.main(Main.java:143)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlElement
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 22 more

The solution of the problem is added JAXB dependency:
     liquibaseRuntime group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.1'

could you please add this information into README.md ?

I also had problem with logback dependency. I solved it with 
  liquibaseRuntime("ch.qos.logback:logback-core:1.2.3")
  liquibaseRuntime("ch.qos.logback:logback-classic:1.2.3") 

Could you please this this information into README.md also? 

Thank you 
Regards Josef

**Comment by stevesaliman** [comment]
I've updated the README to address this.  Thanks for the suggestion.
